### ISSUE TITLE
can you eloborate on this more...what does this exactly mean?

### ISSUE THREAD

**Issue by sirvon** [BranchMetrics/Branch-Integration-Guides#7]
We don't particularly recommend using coupon codes because they are not needed now that Branch links can properly attribute users just through link clicks alone, but we built out a parallel system that works with the links if you absolutely need to use codes. The only reason you should consider this is if you plan to do some promotion of the app with coupon codes on print media and television.

thanks!

**Comment by aaustin** [comment]
@sirvon Sure thing! I hope you're having a great weekend

What we recommend is creating a unique Branch link for every user. For example, call getShortUrl for each user in your app, then put this in the referral message that goes out.

If a new user clicks the Branch link and then installs/opens the app, we automatically track that they originated from the user who sent the link out. You can automatically set up Branch to distribute rewards for referred installs, saving the user time. There's no need for codes or anything!

**Comment by sirvon** [comment]
@aaustin aslong as I get to create, the days are always dandy! 
thanks for the ultra quick response.

I got it now. So as i wanted, if i'm giving users cards/flyers to pass out use the old method where I manually create codes. But if it's all digital just have users use the link that kicks off from getShortUrl method.

old method = physical
standard method = all digital

gotcha! thank you indeed.
